# -*- coding: utf-8 -*-
"""Tugas1A_FitBit_Rizfandino Ramadhan_5026211051.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tYDtk-EhvaiFcrvSnzwXIRCnfRcnWJs

# Tugas 1A FitBit

### Preprocessing dataset
"""

# Import necessary libraries
import pandas as pd
import re
import string
import nltk

# Download required NLTK resources (only need to run these once)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

"""### Tokenization, Stemming, Preprocessing"""

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Define the text preprocessing function with error handling
def preprocess_text(text):
    # If the value is not a string (e.g., NaN), return an empty list
    if not isinstance(text, str):
        return []
    # Convert text to lowercase
    text = text.lower()
    # Remove non-alphabetical characters (retains spaces)
    text = re.sub(r'[^a-z\s]', '', text)
    # Tokenize the text
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    # Initialize the stemmer and apply stemming to each token
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    return tokens

# Load your dataset
df = pd.read_csv('df_fitrev')

# Apply the preprocess_text function on the reviews column
df['cleaned_content'] = df['content'].apply(preprocess_text)

"""### Download cleaned dataset"""

# Save the cleaned DataFrame to a new CSV file
df.to_csv('df_fitrev_cleaned.csv', index=False)

# Display the first few rows of the processed DataFrame
print(df.head())